DROP TABLE IF EXISTS RECIPE_ITEMS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS RECIPES;
DROP TABLE IF EXISTS GROCERY_LIST;

CREATE TABLE ITEMS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_NAME VARCHAR(255) NOT NULL,
    AMOUNT FLOAT NOT NULL,
    UNIT ENUM("tbsp", "tsp", "cup", "oz", "lb")
);

CREATE TABLE RECIPES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RECIPE_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE RECIPE_ITEMS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RECIPE_ID INT,
    ITEM_ID INT,
    AMOUNT FLOAT NOT NULL,
    UNIT ENUM("tbsp", "tsp", "cup", "oz", "lb"),
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES(ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID)
);

CREATE TABLE GROCERY_LIST(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT FLOAT NOT NULL,
    UNIT ENUM("tbsp", "tsp", "cup", "oz", "lb")
);

-- Testing time wooooo
insert into RECIPES (RECIPE_NAME) values ("Pasta");
insert into RECIPES (RECIPE_NAME) values ("Pizza");

insert into ITEMS (ITEM_NAME, AMOUNT, UNIT) values ("Pepperoni", 12, 4);

insert into RECIPE_ITEMS (RECIPE_ID, ITEM_ID, AMOUNT, UNIT) values (2, 1, 2, 4);